---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: Terminal
    path: /wetty
    port: 443

  - name: App UI
    url: 'https://vllm-tool-calling.${openshift_cluster_ingress_domain}'

  - name: OCP Console
    url: '${openshift_console_url}'
